### ISSUE TITLE
Add autoware_lint_common for each package's dependencies

### ISSUE THREAD

**Issue by 1222-takeshi** [autowarefoundation/autoware_common#1]
Use autoware_lint_common instead of amant_lint_common to format in clang-format/Black.

**Comment by kenji-miyake** [comment]
Actually, `amant_lint_common` contains a few linters such as copyright, .cmake, etc.
https://github.com/tier4/tier4_ament_lint/blob/cae03f86e3795e17a225a4f94331acffdfee4587/autoware_lint_common/package.xml

This is because we use `pre-commit` for formatting.

**Comment by 1222-takeshi** [comment]
Merged https://github.com/autowarefoundation/autoware_common/pull/2
