### ISSUE TITLE
Clean folder path `autoware_common/tmp /lanelet2_extension` to `autoware_common/lanelet2_extension`

### ISSUE THREAD

**Issue by felixf4xu** [autowarefoundation/autoware_common#200]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

I don't know why there is a `tmp` folder for `autoware_common/tmp /lanelet2_extension`

### Purpose

clean (remove) the `tmp` folder so that it looks more clean for folder structure

### Possible approaches

remove the `tmp` folder, move `lanelet2_extension` to its upper path

### Definition of done

`tmp` folder is removed

**Comment by isamu-takagi** [comment]
The lanelet2_extension package was moved to this repository by https://github.com/autowarefoundation/autoware_common/issues/84. My understanding is that this is meant for cloning and referencing only lanelet2_extension from other repositories. However, it is not clear whether this repository is suitable as a destination. Therefore, I think that it is placed under tmp directory. We may need to consider moving this package to an independent repository.
