### ISSUE TITLE
`build-and-test.yaml` don't work when pushing to other than `main` or `tier4/proposal`

### ISSUE THREAD

**Issue by h-ohta** [autowarefoundation/autoware_common#21]
According to https://github.com/autowarefoundation/autoware_common/blob/tier4/proposal/.github/workflows/build-and-test.yaml#L5-L7`, build-and-test.yaml` only work when pushing `main` and `tier4/proposal`.

Why don't you add `tier4/universe`? 
Because some of repositories which import it with sync-files workflow has `tier4/universe` repository as a main branch.

Thank you.

**Comment by kenji-miyake** [comment]
@h-ohta I think it should be edited by the user side. Since `tier4/universe` is just TIER IV's naming and there is no relation to AWF, I won't add it.

Let's consider our sync settings. Will close this.

**Comment by h-ohta** [comment]
Thank you for your comments. Let's discuss in tier4.

**Comment by kenji-miyake** [comment]
@h-ohta By the way, as I used here, `${{ github.event.repository.default_branch }}` might be good.
https://github.com/autowarefoundation/autoware-github-actions/blob/349f213850c20738a5bc67a2489c271ca6e33e6f/sync-files/action.yaml#L15

How about this?

**Comment by h-ohta** [comment]
@kenji-miyake I think it's good idea.

**Comment by kenji-miyake** [comment]
Will you send a PR for this? Or should I fix it?

**Comment by h-ohta** [comment]
OK. I'll make it.

**Comment by kenji-miyake** [comment]
There is another problem. The job names conflict.
![image](https://user-images.githubusercontent.com/31987104/152902279-1b558d3f-6ce8-4a45-b20c-ab654054888d.png)

I'll create a new issue for this.
