### ISSUE TITLE
Job names of build-and-test.yaml and build-and-test-pr.yaml conflict

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware_common#28]
After #24 is merged, the job names conflict and the `Required` condition doesn't work correctly.
https://github.com/autowarefoundation/autoware_common/issues/21#issuecomment-1032127058
![image](https://user-images.githubusercontent.com/31987104/152902457-3fe6b3f9-8636-481f-9edd-b1241754807a.png)

**Comment by kenji-miyake** [comment]
I feel changing the job name in `build-and-test-pr.yaml` to "build-and-test-pr", "build-and-test-modified-packages", "build-and-test-differential" is good.

But in that case, we might have to change other job names such as `clang-tidy` or `spell-check` as well for consistency.

@KeisukeShima @h-ohta Do you have any ideas?

**Comment by kenji-miyake** [comment]
Or, changing the condition from "push" to "pull_request is merged" can work? :thinking:

**Comment by KeisukeShima** [comment]
@kenji-miyake I agree with you.
We may also need to change the name of the arm job from "build-and-test-arm".

**Comment by kenji-miyake** [comment]
Which one do you think is the best?

**Comment by kenji-miyake** [comment]
I think, since sometimes we will want to run the full tests on PRs, I'd like to avoid `-pr`.
Also, `modified-packages` is a bit long, so I prefer `differential`.

**Comment by kenji-miyake** [comment]
For example in the future, we can add `prevent-no-label-execution` of the `full-build` label to `build-and-test.yaml` workflow and make it run when the label is added on PRs.

**Comment by KeisukeShima** [comment]
Since we are using `get-modified-packages` in our workflow, we also need to consider its name.
To avoid confusion, I want to change the name of the action if we make it `differential`.

**Comment by kenji-miyake** [comment]
Do you mean changing `get-modified-packages` to `get-differential-packages`? :thinking: 
If so, I feel it's not a big problem.

**Comment by KeisukeShima** [comment]
> Do you mean changing `get-modified-packages` to `get-differential-packages`? thinking If so, I feel it's not a big problem.

Yes. It's not a big problem.

**Comment by kenji-miyake** [comment]
I'll create a PR.
@KeisukeShima By the way, do you think we should add `-amd64` as well? For example, `build-and-test.yaml` will be `build-and-test-amd64.yaml`.

**Comment by kenji-miyake** [comment]
Or instead, should we change the suffix `-arm` to `-self-hosted`?

**Comment by kenji-miyake** [comment]
Considering the reason why I split the ARM workflows, it's because of `self-hosted`, not because of `ARM`, so I think `-self-hosted` might be better.

If ARM machines are supported by GitHub-hosted runners in the future, we can configure matrix jobs in `build-and-test.yaml`.

**Comment by kenji-miyake** [comment]
Also, if we use `-self-hosted`, the users of `sync-files` workflow can understand whether it's necessary for them or not.

With `-arm`, they sometimes try to sync them mistakenly.
https://github.com/autowarefoundation/autoware.universe/blob/2268517328f217dee7f3b6f3dc634af728552b30/.github/sync-files.yaml#L24

**Comment by KeisukeShima** [comment]
Agreed. `-self-hosted` suffix is appropriate.

**Comment by kenji-miyake** [comment]
I sent two PRs!
