### ISSUE TITLE
Start using git tags 

### ISSUE THREAD

**Issue by adamkrawczyk** [autowarefoundation/autoware_common#73]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Hi, 
Since many other projects depend on it, it might be a good idea to start using tags.

### Purpose

No build error in related projects

### Possible approaches

:D

### Definition of done

tagging

**Comment by kenji-miyake** [comment]
> many other projects depend on it

@adamkrawczyk Could you list up some of the projects? (except for the repositories inside the `autowarefoundation` org)
Also, isn't it enough to use commit hashes?

**Comment by adamkrawczyk** [comment]
@kenji-miyake 
I'm not sure if I can tell since they are not open-sourced yet. Last time we noted that at least one branch was deleted causing CI fail. We are using commit hashes, but it would be nice if we could see tagging here - easier to fast check if the dependencies versions are correct. 

I see that you are not much into tagging so if you don't want to go for it it's okay. Just it would be a nice feature.

**Comment by kenji-miyake** [comment]
> Last time we noted that at least one branch was deleted causing CI fail

It was because I deleted the old branch, which shouldn't be dependent.

> I see that you are not much into tagging so if you don't want to go for it it's okay. Just it would be a nice feature.

Hmm, I'm not against using tags.
For example, we use tags for `autoware-github-actions`.
https://github.com/autowarefoundation/autoware-github-actions/releases/tag/v1.7.1

But I don't think tags are necessary for this repository.

**Comment by kenji-miyake** [comment]
In the future, it's good to use tags if necessary. But not necessary for now, I feel.

**Comment by adamkrawczyk** [comment]
I will reopen this issue after two months to ping you ;)
